## Section 11
### Working with Types and NA Values
* 87: Casting Types with astype()
* 88: Introducing the Category Type
* 89: Casting with pd.to_numeric()
* 90: dropna() and isna()
* fillna()

In [1]:
import pandas as pd

In [2]:
houses = pd.read_csv('../datasets/data/kc_house_data.csv')
titanic = pd.read_csv('../datasets/data/titanic.csv')
netflix = pd.read_csv('../datasets/data/netflix_titles.csv', sep='|', index_col=0)
btc = pd.read_csv('../datasets/data/coin_Bitcoin.csv')
countries = pd.read_csv('../datasets/data/world-happiness-report-2021.csv')

In [3]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1309 non-null   str
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: int64(4), str(10)
memory usage: 143.3 KB

In [4]:
titanic.age = titanic.age.replace(['?'], [None])
titanic.age.value_counts(dropna=False)

age
None      263
24         47
22         43
21         41
30         40
         ...
60.5        1
74          1
0.4167      1
11.5        1
26.5        1
Name: count, Length: 99, dtype: int64

In [5]:
titanic.age = titanic.age.astype('float')
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: float64(1), int64(4), str(9)
memory usage: 143.3 KB

In [6]:
titanic.age.mean()

np.float64(29.8811345124283)

In [7]:
titanic.sex = titanic.sex.astype('category')

titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: category(1), float64(1), int64(4), str(8)
memory usage: 134.4 KB

In [8]:
titanic.embarked = titanic.embarked.astype('category')

titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   category
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: category(2), float64(1), int64(4), str(7)
memory usage: 125.5 KB

In [ ]:
pd.to_numeric(titanic.age, errors='coerce')

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [10]:
titanic.age = pd.to_numeric(titanic.age, errors='coerce')

In [11]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   category
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: category(2), float64(1), int64(4), str(7)
memory usage: 125.5 KB

In [14]:
stats = pd.read_csv('../datasets/data/game_stats.csv')
stats

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

In [16]:
stats.league.isna()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
Name: league, dtype: bool

In [17]:
stats.dropna(subset=['rebounds'])

      name league  points  assists  rebounds
0      bob    nba    22.0      5.0      10.0
1   jessie    NaN    10.0      NaN       2.0
3  jackson    aba     9.0      NaN       2.0
5    steph    nba    49.0      8.0      10.0

In [22]:
stats.league = stats.league.fillna('amateur')

In [24]:
stats.fillna(0)

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie     amateur    10.0      0.0       2.0
2       stu  euroleague     0.0      0.0       0.0
3   jackson         aba     9.0      0.0       2.0
4  timothee     amateur     8.0      0.0       0.0
5     steph         nba    49.0      8.0      10.0
6         0     amateur     0.0      0.0       0.0

In [26]:
sales = pd.read_csv('../datasets/data/sales.csv')
sales

   rating  shipping_zip  billing_zip
0     5.0           NaN      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0           NaN      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0

In [29]:
sales['shipping_zip'] = sales['shipping_zip'].fillna(sales['billing_zip'])

In [30]:
sales

   rating  shipping_zip  billing_zip
0     5.0       81220.0      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0       92660.0      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0